# Generated by Django 6.0.3 on 2026-04-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('construction', models.DateField(blank=True, null=True)),
                ('recognized', models.DateField(blank=True, null=True)),
                ('image0', models.ImageField(blank=True, null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image0text', models.CharField(blank=True, max_length=250)),
                ('image1text', models.CharField(blank=True, max_length=250)),
                ('image2text', models.CharField(blank=True, max_length=250)),
                ('significance', models.TextField()),
                ('recognition', models.TextField()),
                ('historical', models.TextField()),
                ('additional', models.TextField()),
                ('mun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.municipality')),
            ],
        ),
    ]
